import sys
import os

"""Variables prefixed with `DEFAULT` should be able to be overridden by
configuration file and command‐line arguments."""

UNIT = 100000000        # The same across assets.


# Versions
VERSION_MAJOR = 9
VERSION_MINOR = 39
VERSION_REVISION = 0
VERSION_STRING = str(VERSION_MAJOR) + '.' + str(VERSION_MINOR) + '.' + str(VERSION_REVISION)


# Counterparty protocol
TXTYPE_FORMAT = '>I'

TWO_WEEKS = 2 * 7 * 24 * 3600
MAX_EXPIRATION = 4 * 2016   # Two months

MEMPOOL_BLOCK_HASH = 'mempool'
MEMPOOL_BLOCK_INDEX = 9999999


# SQLite3
MAX_INT = 2**63 - 1


# Bitcoin Core
OP_RETURN_MAX_SIZE = 40 # bytes


# Currency agnosticism
BTC = 'CRAVE'
XCP = 'BLUR'

BTC_NAME = 'Crave'
BTC_CLIENT = 'craved'
XCP_NAME = 'BLUR'
XCP_CLIENT = 'darkpoold'

DEFAULT_RPC_PORT_TESTNET = 15000
DEFAULT_RPC_PORT = 5000

#TODO: CHANGE THAT UGLY HACK
BACKEND_RPC = 'http://rpcuser:rpcpassword@hostname:9999'
DEFAULT_BACKEND_RPC_PORT_TESTNET = 30107
DEFAULT_BACKEND_RPC_PORT = 30105

UNSPENDABLE_TESTNET = 't6vc3nrbAurGs3i17HJUavZuw4ioKTiFCE'
UNSPENDABLE_MAINNET = 'Bs8Haw3nAsWf5hmLfKzc6PMEzcxUGSYjxf'
UNSPENDABLE = UNSPENDABLE_MAINNET

ADDRESSVERSION_TESTNET = b'\x7f'
# PRIVATEKEY_VERSION_TESTNET =
ADDRESSVERSION_MAINNET = b'\x1b'
# PRIVATEKEY_VERSION_MAINNET =
MAGIC_BYTES_TESTNET = b'\x1f\x22\x05\x31'   # For bip-0010
MAGIC_BYTES_MAINNET = b'\x1f\x22\x05\x30'   # For bip-0010

WIF_PREFIX_TESTNET = b'\xef'
WIF_PREFIX_MAINNET = b'\x99'

BLOCK_FIRST_TESTNET_TESTCOIN = 10
BURN_START_TESTNET_TESTCOIN = BLOCK_FIRST_TESTNET_TESTCOIN
BURN_END_TESTNET_TESTCOIN = 26280000    # Fifty years, at 1 minute per block.

BLOCK_FIRST_TESTNET = BLOCK_FIRST_TESTNET_TESTCOIN
BURN_START_TESTNET =  BURN_START_TESTNET_TESTCOIN
BURN_END_TESTNET = 26280000             # Fifty years, at 1 minute per block.

BLOCK_FIRST_MAINNET_TESTCOIN = 17000
BURN_START_MAINNET_TESTCOIN = BLOCK_FIRST_MAINNET_TESTCOIN
BURN_END_MAINNET_TESTCOIN = 26280000    # Fifty years, at 1 minute per block.

BLOCK_FIRST_MAINNET = BLOCK_FIRST_MAINNET_TESTCOIN
BURN_START_MAINNET = BURN_START_MAINNET_TESTCOIN
BURN_END_MAINNET = BURN_START_MAINNET + 30*24*60    # 30 days burn period with 1 min target time per block.

MAX_BURN_BY_ADDRESS = 1000 * UNIT 	# 1K CRAVE.
BURN_MULTIPLIER = 5 				        # from 7.5 to 5 BLUR per 1 CRAVE.

# Protocol defaults
# NOTE: If the DUST_SIZE constants are changed, they MUST also be changed in counterblockd/lib/config.py as well
DEFAULT_REGULAR_DUST_SIZE = UNIT * 0.00001000		  # 1 DOGE; there is not dust limit in Dogecoin, but every txout < 1 DOGE, cost 1 DOGE in fee
DEFAULT_MULTISIG_DUST_SIZE = UNIT * 0.00001000 # 2 DOGE.
DEFAULT_OP_RETURN_VALUE = 0 			    # 0 DOGE.
DEFAULT_FEE_PER_KB = UNIT * 0.00010000            # 1 DOGE.
BACKEND_RPC_SSL_VERIFY = False

# UI defaults
DEFAULT_FEE_FRACTION_REQUIRED = .009   # 0.90%
DEFAULT_FEE_FRACTION_PROVIDED = .01    # 1.00%
UNITTEST = False
CAREFULNESS = 0
